# Generated by Django 4.1.13 on 2024-04-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image_product_thumbnail'),
        ('product', '0005_product_image_product_thumbnail'),
    ]

    operations = [
    ]
